version: '3'
services:
  influxdb:
    image: influxdb:1.8
    # environment: 
    #   INFLUXDB_REPORTING_DISABLED: "true"
    #   INFLUXDB_DB: "metrics"
    #   INFLUXDB_ADMIN_USER: "admin"
    #   INFLUXDB_ADMIN_PASSWORD: "admin"
    #   INFLUXDB_USER: "telegraf"
    #   INFLUXDB_USER_PASSWORD: "telegraf"
    #   INFLUXDB_HTTP_AUTH_ENABLED: "true"
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:8.1.7
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
